version: "3"

services:
  app:
    build: ./user_app
    ports:
      - 8002:8000
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
    volumes:
      - ./user_app:/user_app

  mongo:
    image: mongo:latest
    ports:
      - 27019:27017
    volumes:
      - ./data/db:/data/db